module.exports={
    configurewebpack:{
        resolve:{
            alias:{
                'assets':'@/assets',
                'network':'@/network',
                'views':'@/views',
                'components':'@/components'
            }
        }
    }
}